# Generated by Django 2.1.2 on 2018-10-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_historyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyprice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
