# Generated by Django 2.1.2 on 2018-10-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20181007_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyprice',
            old_name='id',
            new_name='index',
        ),
    ]
