# Generated by Django 2.1.2 on 2018-10-07 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20181007_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyprice',
            name='id',
            field=models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True),
        ),
    ]
