# Generated by Django 2.1.2 on 2018-10-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20181007_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyprice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
