# Generated by Django 2.1.2 on 2018-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20181007_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyprice',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
